version: '3'
services:
  app:
    build:
      context: .
      args:
        - REACT_APP_weatherApi=${REACT_APP_weatherApi}
        - REACT_APP_geminiApi=${REACT_APP_geminiApi}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_weatherApi=${REACT_APP_weatherApi}
      - REACT_APP_geminiApi=${REACT_APP_geminiApi}