name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set environment variables
        run: |
          echo "REACT_APP_weatherApi=${{ secrets.REACT_APP_WEATHERAPI }}" >> $GITHUB_ENV
          echo "REACT_APP_geminiApi=${{ secrets.REACT_APP_GEMINIAPI }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build